'use client';
import {useMemo,useState} from 'react';

const products=[
{id:'starter',name:'Starter Strandvisset',tag:'Meest gekozen',price:27.50,deposit:50,category:'sets',image:'/starter.svg',description:'Een complete, gebruiksklare set voor een ontspannen eerste visdag vanaf het strand.',includes:['4,20 m strandhengel','Zeemolen met lijn','Strandsteun','Onderlijn en lood']},
{id:'duo',name:'Duo Strandvispakket',tag:'Voordelig samen',price:49.50,deposit:90,category:'sets',image:'/duo.svg',description:'Twee volledige sets voor vrienden, stellen of ouder en kind.',includes:['2 complete strandvissets','2 strandsteunen','Basis kleinmateriaal','Persoonlijke uitleg']},
{id:'family',name:'Familie Visavontuur',tag:'Voor 3 personen',price:72.50,deposit:125,category:'sets',image:'/family.svg',description:'Alles wat je nodig hebt voor een gezamenlijke middag vissen aan zee.',includes:['3 complete vissets','Ruime viskar','Emmers en kleinmateriaal','Startuitleg']},
{id:'premium',name:'Premium Zeevisset',tag:'Voor gevorderden',price:34.50,deposit:75,category:'sets',image:'/premium.svg',description:'Een krachtige set voor wie gericht op platvis, zeebaars of gul wil vissen.',includes:['Premium strandhengel','Robuuste zeemolen','Gevlochten hoofdlijn','Zwaardere strandsteun']},
{id:'cart',name:'Strandkar',tag:'Handige extra',price:12.50,deposit:30,category:'extras',image:'/cart.svg',description:'Vervoer hengels, stoelen, emmers en aas eenvoudig over het strand.',includes:['Brede strandwielen','Ruimte voor meerdere sets','Inklapbaar frame','Maximaal 40 kg']},
{id:'waders',name:'Waadpak',tag:'Diverse maten',price:17.50,deposit:40,category:'extras',image:'/waders.svg',description:'Blijf droog bij het inzetten van de lijn of vissen langs de waterlijn.',includes:['Maten 40 t/m 47','Verstelbare bretels','Stevige laarzen','Gereinigd na gebruik']},
{id:'bait',name:'Zeeaas pakket',tag:'Direct mee te boeken',price:9.50,deposit:0,category:'bait',image:'/bait.svg',description:'Een praktisch aas-pakket voor één visser en één visdag.',includes:['Zagers of pieren','Koel verpakt','Geschikt voor strandvisserij','Beschikbaarheid op aanvraag']}
];
const money=v=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(v);
export default function HomePage(){
 const [selected,setSelected]=useState({starter:1}); const [category,setCategory]=useState('all'); const [status,setStatus]=useState('');
 const [details,setDetails]=useState({startdatum:'',einddatum:'',ophaaltijd:'',verblijf:''});
 const chosen=useMemo(()=>products.filter(p=>(selected[p.id]||0)>0),[selected]);
 const daily=useMemo(()=>products.reduce((s,p)=>s+(selected[p.id]||0)*p.price,0),[selected]);
 const deposit=useMemo(()=>products.reduce((s,p)=>s+(selected[p.id]||0)*p.deposit,0),[selected]);
 const filtered=products.filter(p=>category==='all'||p.category===category);
 const qty=(id,d)=>setSelected(v=>({...v,[id]:Math.max(0,(v[id]||0)+d)}));
 async function submitForm(e){e.preventDefault();if(!chosen.length){setStatus('Kies eerst minimaal één product.');return;}setStatus('Je aanvraag wordt verstuurd…');const f=new FormData(e.currentTarget);const payload={naam:f.get('naam'),email:f.get('email'),telefoon:f.get('telefoon'),verblijf:f.get('verblijf'),startdatum:f.get('startdatum'),einddatum:f.get('einddatum'),ophaaltijd:f.get('ophaaltijd'),ervaring:f.get('ervaring'),opmerkingen:f.get('opmerkingen'),items:chosen.map(p=>({id:p.id,naam:p.name,aantal:selected[p.id],prijs:p.price})),totaal:daily,borg:deposit};try{const r=await fetch('/api/aanvragen',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw Error();setStatus('Bedankt! Joran neemt zo snel mogelijk contact met je op.');}catch{const saved=JSON.parse(localStorage.getItem('strandvis-aanvragen')||'[]');saved.unshift({...payload,id:crypto.randomUUID(),status:'Nieuw',created_at:new Date().toISOString()});localStorage.setItem('strandvis-aanvragen',JSON.stringify(saved));setStatus('Bedankt! Je aanvraag is opgeslagen. Joran neemt contact met je op.');}}
 return <main>
 <div className="topbar"><span>Lokale verhuur op Ameland</span><span>Contactpersoon: Joran Kuiper</span><a href="tel:+31652629982">+31 6 52629982</a></div>
 <header className="nav"><a className="brand" href="#top"><img src="/logo-horizontal.svg" alt="Strandvis Verhuur Ameland"/></a><nav><a href="#aanbod">Verhuuraanbod</a><a href="#uitleg">Strandvissen</a><a href="#contact">Contact</a></nav><a className="button small primary" href="#aanvragen">Reserveren</a></header>
 <section className="hero" id="top"><div className="hero-content"><span className="eyebrow light">VISSEN AAN DE WADDENZEE</span><h1>Hengels huren op Ameland</h1><p>Complete strandvissets, handige extra’s en vers zeeaas. Alles staat gebruiksklaar voor jouw visdag.</p><div className="hero-actions"><a className="button primary" href="#aanbod">Bekijk het aanbod</a><a className="button glass" href="#aanvragen">Direct aanvragen</a></div></div><div className="hero-card"><span className="live-dot">Beschikbaar op aanvraag</span><h3>Complete strandvisset</h3><p>Vanaf</p><strong>{money(27.5)}<small> per dag</small></strong><ul><li>Hengel en molen</li><li>Steun, lood en onderlijn</li><li>Persoonlijke uitleg</li></ul></div></section>
 <section className="usp-strip"><div><b>✓</b><span><strong>Complete sets</strong><small>Direct gebruiksklaar</small></span></div><div><b>✓</b><span><strong>Zeeaas bijboeken</strong><small>Praktisch aas-pakket</small></span></div><div><b>✓</b><span><strong>Lokaal ophalen</strong><small>Op Ameland</small></span></div><div><b>✓</b><span><strong>Persoonlijk advies</strong><small>Door Joran Kuiper</small></span></div></section>
 <section className="section sand" id="aanbod"><div className="section-heading"><div><span className="eyebrow">VERHUURAANBOD</span><h2>Kies wat je nodig hebt</h2></div><p>Alle materialen worden schoon, gecontroleerd en compleet uitgegeven. Aas kun je direct meeboeken.</p></div><div className="filter-tabs">{[['all','Alles'],['sets','Complete sets'],['extras','Extra materiaal'],['bait','Aas']].map(([id,l])=><button key={id} className={category===id?'active':''} onClick={()=>setCategory(id)}>{l}</button>)}</div><div className="cards">{filtered.map(p=><article className="card" key={p.id}><div className="product-image" style={{backgroundImage:`url(${p.image})`}}><span>{p.tag}</span></div><div className="card-body"><h3>{p.name}</h3><p>{p.description}</p><ul>{p.includes.map(x=><li key={x}>{x}</li>)}</ul><div className="card-footer"><div><strong>{money(p.price)}</strong><small>{p.category==='bait'?' per pakket':' per dag'}</small></div><div className="qty"><button onClick={()=>qty(p.id,-1)}>−</button><span>{selected[p.id]||0}</span><button onClick={()=>qty(p.id,1)}>+</button></div></div></div></article>)}</div></section>
 <section className="section dark-section" id="uitleg"><div className="section-heading"><div><span className="eyebrow light">STRANDVISSEN OP AMELAND</span><h2>Alles voor een ontspannen visdag</h2></div><p>Joran helpt je met materiaalkeuze, uitleg en praktische tips voor het vissen vanaf het Amelander strand.</p></div><div className="info-grid"><article><span>🌊</span><h3>Getij en omstandigheden</h3><p>Vraag bij je aanvraag gerust om advies over wind, getij en geschikte momenten.</p></article><article><span>🐟</span><h3>Wat kun je vangen?</h3><p>Afhankelijk van het seizoen onder andere schar, bot, wijting en zeebaars.</p></article><article><span>🪱</span><h3>Aas direct geregeld</h3><p>Boek een gekoeld aas-pakket mee en vertrek zonder extra tussenstop naar het strand.</p></article></div></section>
 <section className="section request" id="aanvragen"><form className="form" onSubmit={submitForm}><div className="form-title"><span>Reservering aanvragen</span><small>Vrijblijvende aanvraag</small></div><div className="steps"><span className="active">1 Gegevens</span><span>2 Huurperiode</span><span>3 Versturen</span></div><h3>Jouw gegevens</h3><div className="grid2"><label>Naam *<input name="naam" required placeholder="Voor- en achternaam"/></label><label>Telefoonnummer *<input name="telefoon" required placeholder="06 12 34 56 78"/></label></div><label>E-mailadres *<input name="email" type="email" required placeholder="naam@email.nl"/></label><h3>Huurperiode</h3><label>Verblijfsadres op Ameland<input name="verblijf" value={details.verblijf} onChange={e=>setDetails({...details,verblijf:e.target.value})} placeholder="Vakantiepark, hotel of adres"/></label><div className="grid2"><label>Ophaaldatum *<input name="startdatum" type="date" required value={details.startdatum} onChange={e=>setDetails({...details,startdatum:e.target.value})}/></label><label>Retourdatum *<input name="einddatum" type="date" required value={details.einddatum} onChange={e=>setDetails({...details,einddatum:e.target.value})}/></label></div><div className="grid2"><label>Gewenste ophaaltijd<select name="ophaaltijd" value={details.ophaaltijd} onChange={e=>setDetails({...details,ophaaltijd:e.target.value})}><option value="">Kies een tijd</option><option>08:00 - 10:00</option><option>10:00 - 12:00</option><option>12:00 - 14:00</option><option>14:00 - 16:00</option></select></label><label>Ervaringsniveau<select name="ervaring"><option>Beginner / eerste keer</option><option>Enige ervaring</option><option>Ervaren zeevisser</option></select></label></div><label>Vragen of bijzonderheden<textarea name="opmerkingen" rows="4" placeholder="Bijvoorbeeld gewenste maten, aas of extra uitleg"/></label><label className="consent"><input type="checkbox" required/><span>Ik begrijp dat dit een aanvraag is en nog bevestigd moet worden.</span></label><button className="button primary wide">Verstuur aanvraag →</button>{status&&<p className="status">{status}</p>}</form>
 <aside className="booking-summary"><div className="summary-head"><div><span>Jouw reservering</span><small>Direct bijgewerkt</small></div><a href="#aanbod">Wijzig</a></div><div className="summary-items">{chosen.length?chosen.map(p=><div className="summary-item" key={p.id}><img src={p.image} alt=""/><div><strong>{p.name}</strong><small>{selected[p.id]} × {money(p.price)}</small></div><b>{money(selected[p.id]*p.price)}</b></div>):<p>Nog geen producten geselecteerd.</p>}</div><div className="summary-meta"><div><span>Ophaaldatum</span><strong>{details.startdatum||'Nog kiezen'}</strong></div><div><span>Retourdatum</span><strong>{details.einddatum||'Nog kiezen'}</strong></div><div><span>Ophaaltijd</span><strong>{details.ophaaltijd||'In overleg'}</strong></div><div><span>Verblijf</span><strong>{details.verblijf||'Nog invullen'}</strong></div></div><div className="summary-total"><div><span>Huurprijs per dag</span><strong>{money(daily)}</strong></div><div><span>Indicatieve borg</span><strong>{money(deposit)}</strong></div></div><div className="summary-contact"><span>Vragen over je aanvraag?</span><strong>Joran Kuiper</strong><a href="tel:+31652629982">+31 6 52629982</a></div></aside></section>
 <section className="section contact" id="contact"><div><span className="eyebrow light">CONTACT</span><h2>We helpen je graag</h2><p>Voor vragen, groepen of meerdaagse verhuur kun je Joran bellen of WhatsAppen.</p><div className="contact-actions"><a href="tel:+31652629982">+31 6 52629982</a><a href="mailto:info@strandvisverhuurameland.nl">info@strandvisverhuurameland.nl</a></div></div><div className="contact-card"><span>Contactpersoon</span><strong>Joran Kuiper</strong><p>Dagelijks bereikbaar op afspraak</p><hr/><span>Ophaalpunt</span><strong>Nes, Ameland</strong><p>Exacte locatie na bevestiging</p></div></section>
 <footer><div className="footer-main"><img src="/logo-horizontal.svg" alt="Strandvis Verhuur Ameland"/><p>Complete strandvissets, extra materiaal en aas voor een zorgeloze visdag op Ameland.</p></div><div><strong>Navigatie</strong><a href="#aanbod">Verhuuraanbod</a><a href="#aanvragen">Reserveren</a><a href="#contact">Contact</a></div><div><strong>Contact</strong><a href="tel:+31652629982">+31 6 52629982</a><a href="mailto:info@strandvisverhuurameland.nl">E-mail versturen</a><a href="/admin">Admin dashboard</a></div><div className="footer-bottom">© 2026 Strandvis Verhuur Ameland</div></footer>
 </main>
}
